import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import  BreadcrumbBasic from "@/components/BreadcrumbBasic";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="fr" suppressHydrationWarning className="h-full">
         <body className={cn(geistSans.variable, geistMono.variable)}>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <div className="absolute top-1 right-1">
                  <ModeToggle />
               </div>
               <div className="flex flex-col w-full items-center py-5 px-5">
                  <BreadcrumbBasic />
                  {children}
               </div>
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
