import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="fr" suppressHydrationWarning className="h-full">
         <body className={cn(geistSans.variable, geistMono.variable)}>
            <ThemeProvider
               attribute="class"
               defaultTheme="light"
               enableSystem
               disableTransitionOnChange
            >
               <div className="flex flex-col align-items gap-3 px-5 py-5">
                  <div className="absolute top-0 right-0 px-1 py-1">
                     <ModeToggle />
                  </div>
                  {children}
               </div>
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
